CREATE TABLE articles (
  `id`      INT(36) UNSIGNED NOT NULL AUTO_INCREMENT,
  userId    VARCHAR(64)      NOT NULL,
  url       TEXT             NOT NULL,
  title     VARCHAR(255),
  createdAt TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE user_codes (
  `id`      INT(36) UNSIGNED NOT NULL AUTO_INCREMENT,
  userId    VARCHAR(64)      NOT NULL,
  code      VARCHAR(64)      NOT NULL,
  createdAt TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

